

services:
  app:
    build: .
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    env_file:
      - .env 

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    env_file:
      - .env